services:
  solana:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $PWD:/mnt
    ports:
      - "8899:8899"
      - "8900:8900"
    tty: true
    stdin_open: true
    restart: unless-stopped
