services:
  solana:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $HOME/.zshrc:/root/.zshrc
      - $PWD:/root/home/
    tty: true
    stdin_open: true
    restart: unless-stopped